Issue2:First commit on feature/ecs-setup
hamada-fatma/Pipeline- pull request #5
Opened 2024-08-29 09:01 UTC by hamada-fatma

2024-09-07 09:42 UTC, Ismail-Hamada requested changes

2024-09-07 09:42 UTC, Ismail-Hamada commented on main.tf
> +  security_groups = [module.ecs.lb_sg_id]
it's already a resource within the same module, why use outputs?

2024-09-07 09:42 UTC, Ismail-Hamada commented on main.tf
> +  target_group_name  = "web-traffic-tg"
what if we need more than a single target group?

2024-09-15 22:40 UTC, Ismail-Hamada approved these changes

2024-09-17 17:02 UTC, hamada-fatma commented
Issue2: Implement Network and ECS modules

2024-09-17 17:24 UTC, hamada-fatma commented
Implement Network and ECS modules

2024-09-17 17:27 UTC, hamada-fatma commented
Implement Network and ECS modules

2024-09-17 17:27 UTC, merged